### ISSUE TITLE
Tidy data oblika tabele

### ISSUE THREAD

**Issue by larajagodnik** [larajagodnik/APPR-2018-19#1]
Težave imam z tabelama zenske in moski, v uvozu svetovnih prvenstev 2005-2017.
Podatki za naprimer 100m so v sekundah, za maraton v urah zapisano v obliki h : m : s , zraven pa se opomba o osebnih rekordih in podobno. Iz tega ne znam dobiti ven samo številke, da bi lahko delala z rezultati. Zanima me tudi kako bi to tabelo spremenila v tidy data.

Drugo težavo imam v uvozu populacija. V tabeli populacija sem v stolpcu prebivalstvo izracunala povprecno stevilo prebivalcev. Vsoto vseh prebivalcev drzave sem delila s 16 (leta za katere imam podatke v katerih je bilo svetovno prvenstvo) a to ni vredu, ker nekatere države nimajo podatkov za vsa leta.

**Comment by jaanos** [comment]
Najprej bi opozoril na velikosti črk pri navajanju imen datotek. Programi v mapi `uvoz` imajo končnico `.R` (velika črka!), tako da to uporabi tudi, ko jih v `projekt.Rmd` kličeš s `source`. Svetujem še, da se raje izogibaš presledkom v imenih datotek (pa tudi šumnikom in drugim posebnim znakom).

Kar se tiče rezultatov, bo bolje, če imaš ločene tekaške discipline (rezultati so časi) in tehnične discipline (rezultati so razdalja - razen sedmeroboja in deseteroboja, ki ga lahko izločiš). Združena razpredelnica bo vseeno prišla prav, da pretvorbo v *tidy data* opraviš samo enkrat:
```R
stolpci <- c("disciplina", "tekmovalec1", "rezultat1", "tekmovalec2", "rezultat2",
             "tekmovalec3", "rezultat3", "leto")
names(zenske) <- stolpci
names(moski) <- stolpci
vsi.rezultati <- rbind(zenske %>% mutate(spol="Ženski"),
                       moski %>% mutate(spol="Moški")) %>%
  transmute(disciplina, leto, spol,
            `1`=paste0(tekmovalec1, "_", rezultat1),
            `2`=paste0(tekmovalec2, "_", rezultat2),
            `3`=paste0(tekmovalec3, "_", rezultat3)) %>%
  melt(id.vars=c("disciplina", "leto", "spol"), variable.name="uvrstitev") %>%
  separate(value, c("tekmovalec", "rezultat"), "_") %>%
  filter(tekmovalec != "")
```

Sedaj lahko podatke spet ločiš. Pri tekaških disciplinah bo treba izluščiti čase iz nizov - sekunde so povsod navedene, pred njimi so s podpičji ločene minute in morda še ure, za njimi pa so s piko ali vejico ločene še stotinke. Kar sledi, so sami neštevilski znaki - te bomo ignorirali. Ta zapis bo treba poenotiti (v manjkajoča polja se vstavijo ničle), da se potem lahko pretvori v čas s `parse_time`:
```R
tekaske <- unique(c(rezultati.moski.tekaske[[1]], rezultati.zenske.tekaske[[1]]))
options(digits.secs=2) # sekunde so izražene z dvema decimalkama
rezultati.tekaske <- vsi.rezultati %>% filter(disciplina %in% tekaske) %>%
  mutate(rezultat=strapplyc(rezultat,
                            "^(?:([0-9]+):)??(?:([0-9]+):)?([0-9]+)(?:[.,]([0-9]+))?[^0-9]*$") %>%
           sapply(function(x) do.call(sprintf, c("%02d:%02d:%02d.%02d",
                                                 parse_number(x) %>% coalesce(0) %>%
                                                   as.list()))) %>%
           parse_time("%H:%M:%OS"))
```
Podobno lahko potem narediš še za tehnične discipline (rezultati v metrih) in sedmeroboj/deseteroboj (rezultati v točkah), le da bo tam pretvorba v števila enostavnejša - lahko uporabiš kar `parse_number` z ustrezno nastavitvijo ločila decimalk (spet se pojavlja tako pika kot vejica, tako da lahko pred pretvorbo eno zamenjaš z drugo).

Kar se tiče razpredelnice `populacija`, lahko povprečje izračunaš s funkcijo `mean`. Tako kot `sum` ta sprejme parameter `na.rm` - če je nastavljen na `TRUE`, se manjkajoče vrednosti ne upoštevajo pri izračunu (tj., vsota se deli s številom obstoječih vrednosti):
```R
populacija <- melt(uvozi.populacija, value.name="število", na.rm=FALSE) %>% 
  group_by(država) %>% summarize(prebivalstvo=mean(število, na.rm=TRUE))
```
Svetujem sicer, da se v imenih stolpcev izogibaš uporabi šumnikov (pa tudi presledkov in drugih posebnih znakov).

Na tej točki podatkov ne zaokrožuj in jih ne deli - če bo potrebno, lahko to storiš ob izrisovanju podatkov na graf ali zemljevid. Nove vrstice lahko pri dodajanju v razpredelnico predstaviš kot sezname - tako imajo lahko vrednosti različne tipe in zato ni potrebna ponovna pretvorba s `parse_number`:
```R
populacija <- rbind(populacija, list("Czechoslovakia", 15600000))
```

**Comment by larajagodnik** [comment]
Hvala!
