### ISSUE TITLE
Zemljevid

### ISSUE THREAD

**Issue by larajagodnik** [larajagodnik/APPR-2018-19#3]
Pozdravljeni,
težave imam z uvozom zemljevida.
Uporabila sem isto kodo kot eden od mojih sošolcev in na faksu je vse delovalo, na domačem računalniku pa imam težave.
Napaka ki jo dobim:

Error in download.file(url, zip) : 
  cannot open destfile '../zemljevidi/f5e4b4ad73a46f2d63eefa0eec602470852ff408/f5e4b4ad73a46f2d63eefa0eec602470852ff408.zip', reason 'No such file or directory'
In addition: Warning message:
In dir.create(map, recursive = TRUE) :
  cannot create dir '..', reason 'Permission denied'

Hvala in lep pozdrav

**Comment by jernejbanevec** [comment]
Meni tvoj uvoz zemljevida deluje. Za vsak slučaj poskusi ponovno namestiti in uvoziti vse potrebne knjižice za uvoz zemljevida: `rgdal`, `dplyr`, `readr`, `digest` in `mosaic`.
Lahko pa poskusiš spremeniti mapo, v katero naj ti `R` shrani zemljevid, npr.:
```r
zemljevid <- uvozi.zemljevid("https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/50m/cultural/ne_50m_admin_0_countries.zip",
                             "ne_50m_admin_0_countries",mapa="./zemljevidi") %>% fortify()
```
kjer namesto privzete vrednosti `mapa = ../zemljavidi`, uporabi vrednost kjer imaš nastavljen `working directory` (zdi se namreč, da `R` ne more najti mape kamor želiš ti shraniti zemljevid - morda takšna mapa tudi ne obstaja na tvojem računalniku). Ti to morda kako pomaga?

**Comment by larajagodnik** [comment]
Najlepša hvala, spremenjena mapa v katero R shrani zemljevid je rešila težavo.

**Comment by larajagodnik** [comment]
Pozdravljeni,
sedaj imam težave z analizo. Če kodo v analiza.r zaženem vsako posebej mi ta deluje, v poročilu projekta pa pri source("analiza/analiza.r", encoding="UTF-8") dobim napako:
invalid input found on input connection 'analiza/analiza.r'

Zanima me kaj bi lahko bilo narobe, saj mi nobene tabele, ki sem jo definirala v analizi ne naredi.
Lep pozdrav

**Comment by jaanos** [comment]
Do take napake navadno pride, če je program, ki ga kličeš, shranjen z napačnim kodiranjem znakov (v tem primeru torej ne v UTF-8). Sam sicer ne vidim, kaj bi bilo narobe - pri meni namreč deluje, prav tako na Binderju. Ali imaš zadnjo različico naloženo na GitHub? @jernejbanevec, lahko prosim še ti preveriš, če prihaja do problemov?

**Comment by larajagodnik** [comment]
Ja, na Gitu imam zadnjo različico. Bom preverila še na faksu ali deluje.
Hvala
