### ISSUE TITLE
Povezava za RStudio v Binderju

### ISSUE THREAD

**Issue by jaanos** [larajagodnik/APPR-2018-19#4]
Vidim, da si v poročilu zakomentirala klic programa `rstudio.r`:

https://github.com/larajagodnik/APPR-2018-19/blob/b8ed1acdf1d0585ae9cfc609a3de41beb8d70cce/projekt.Rmd#L22-L25

Pri lokalnem prevajanju poročila to sicer ničesar ne spremeni, pri poganjanju na Binderju pa ta vrstica poskrbi za izris povezave za odpiranje projekta v RStudiu v brskalniku. Svetujem torej, da vrstico 24 odkomentiraš.

Prav tako opažam, da si v commitu c8e933d851606d5963d64cc9b11d50bb72a59bd0 iz mape `slike` pobrisala datoteko [`RStudio.png`](https://github.com/jaanos/APPR-2018-19/blob/master/slike/RStudio.png). Svetujem, da jo vrneš tja, da se bo povezava pokazala s sliko.

**Comment by larajagodnik** [comment]
Najlepša hvala!
